### PR TITLE
Standardized for SN Extensions repo

### PR DESCRIPTION
**Pull request by xthursdayx**
I updated and standardized the directory structure and code to match the current Standard Notes themes formatting, and also created a tagged release to allow for the inclusion of this theme in the [Standard Notes Extensions Self-Hosted Repository](https://github.com/iganeshk/standardnotes-extensions). I'll be happy to correct the repo links in the `ext.json` file (and elsewhere) if this PR is merged (replacing(replacing `xthursdayx`, which is there temporarily to get this repo to work with SN, with `hyphone`.

I realize that you did away with the use of `grunt` in favour of `chokidar-cli` and `node-sass` in your `1.1.0` release, and removed the `dist` directory, so in some ways this PR is a step backwards. However, in order to get this theme to work with SN Extensions Self-Hosted Repository it is necessary to match the file structure etc. NPM also found 14 vulnerabilities when using `chokidar` and `node-sass`, though I guess that doesn't really matter. However, since this PR includes other changes (e.g. the removal of the build script and changes to ext.json) I'm fine if you would prefer not to merge it. I can keep my fork up to date with yours in order to have a version that work with the self-hosted extension repo. Cheers.

### CODE REVIEW

**Comment by marcolaux** [comment]
Thanks for having a look.
Could you include the build script again though? It really helps me with debugging when it pushes the files directly to the directory so I just have to refresh SN.

**Comment by marcolaux** [comment]
If you would link it back to my repo I'm happy to accept it if this can be used then in the Self-Hosted Repo.
I like it and use it myself and hope that others also find use for it. :v:

**Comment by marcolaux** [comment]
It is merged and I also made a new release.
Thank you again!

I added two npm scripts again that executes the grunt scripts so only rubygem-sass is needed as a local dependency and grunt can be executed within the npm context.

**Comment by marcolaux** [comment]
sadly I was not able to see the styles on the mobiles editor and I freaking don't know why.

I tried everything and I can't get them to load when I point the things to github and in a seperate dist folder.
I deleted all the data after every step on android and the current master (self hosted) is the only way I can see the editor styles on mobile.

If you have any idea how to be compliant with the self hosted extension repo and how to get the editor styles working this way I'm open for a new PR of course.

But at the moment I'm out of ideas, tried every combination with the paths in combination with github possible.

Perhaps you can try it with your repo to delete the android app data, remove it the theme from desktop, add it again, and start the mobile app from scratch.

**Comment by xthursdayx** [comment]
Thanks for your work on this! I'll look into the issue with the mobile editor and see if I can figure out what the problem is. I assume that it may be a CORS issue as I know that this has been a problem for some other themes and the reason that people people often used non-GH hosting for their `json` files, but tbh I'm not really sure how to fix that. I'll play around with the repo and NGINX though to see if I can get it to work.

**Comment by marcolaux** [comment]
I have to admit I did a lot of trial and error testing and with GH hosting I always ran into the issue that the editor styles were not applied. Because of the lack of time I did not compile the Android app for myself so I did not have the possibility to really debug this.

I tried the following:
- GH for hosting, dist.css in `dist/dist.css`
- GH for hosting, dist.css in `dist.css`
- self hosting, dist.css in `dist/dist.css`
- self hosting, dist.css in `dist.css`

Only in the last scenario I iwas able to have the editors on mobile styled.

It could be indeed that the GH caching in combination with the SN caching played a role in this and some scenarios overlapped.

I'm also not sure if the .zip is loaded in the app or if the .css is directly loaded. So I also reverted the zip back to my own zip as the github master zip always contains an additional folder at root. I'm also not really sure if this could be a cultprint.

**Comment by marcolaux** [comment]
At least the current master branch is working for me - I ran the app on Android in a clean state, applied the theme and it works niceley now.

I also would like to host it directly at GH and I will also have a look hopefully next week into this when I find 1 or 2 hours (then in a seperate branch to not mess with things like I did today - when I'm stressed I tend to rush things sometimes - you could tell when you see all those commits -_-° ).

**Pull request merged**
